const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.CompareAcceleration,
		C3.Behaviors.EightDir.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{ScrollTo: 0},
	{Sprite: 0},
	{ถนน: 0},
	{ฟ้า: 0},
	{โรงบาล: 0},
	{มหาลัย: 0},
	{Keyboard: 0},
	{wegota: 0},
	{BikeBoulevard: 0},
	{NextCompany: 0},
	{ป้ายการศึกษา: 0},
	{ป้ายประสบการณ์: 0},
	{Sine: 0},
	{Logo: 0},
	{Name: 0},
	{MyStore: 0},
	{MySkills: 0},
	{SKILL_ID: 0},
	{RedBox: 0},
	{Warp: 0},
	{ป้ายWarp: 0},
	{Browser: 0},
	{Audio: 0},
	{Touch: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	ถนน: class extends self.ITiledBackgroundInstance {},
	ฟ้า: class extends self.ITiledBackgroundInstance {},
	โรงบาล: class extends self.ITiledBackgroundInstance {},
	มหาลัย: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	wegota: class extends self.ITiledBackgroundInstance {},
	BikeBoulevard: class extends self.ITiledBackgroundInstance {},
	NextCompany: class extends self.ITiledBackgroundInstance {},
	ป้ายการศึกษา: class extends self.ITiledBackgroundInstance {},
	ป้ายประสบการณ์: class extends self.ITiledBackgroundInstance {},
	Logo: class extends self.ISpriteInstance {},
	Name: class extends self.ISpriteInstance {},
	MyStore: class extends self.ITiledBackgroundInstance {},
	MySkills: class extends self.ISpriteInstance {},
	RedBox: class extends self.ISpriteInstance {},
	Warp: class extends self.ISpriteInstance {},
	ป้ายWarp: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {}
}